source 'https://github.com/CocoaPods/Specs.git'


target 'SZNZoteroDemo' do
    platform :ios, '7.0'
    pod 'SZNZotero', :path => '../../'
end

target 'SZNZoteroTests' do
    platform :ios, '7.0'
    pod 'SZNZotero', :path => '../../'
end

target 'SZNZoteroDemoOSX' do
    platform :osx, '10.8'
    pod 'SZNZotero', :path => '../../'
end

target 'SZNZoteroTestsOSX' do
    platform :osx, '10.8'
    pod 'SZNZotero', :path => '../../'
end
