
target 'SZNZoteroDemo', :exclusive => false do
    platform :ios, '6.0'
    pod 'SZNZotero', :path => '../../'
end

target 'SZNZoteroDemoOSX', :exclusive => false do
    platform :osx, '10.8'
    pod 'SZNZotero', :path => '../../'
end
